// REACT_APP_CONFIRMATION_NUMBER = 3
// REACT_APP_AVERAGE_BLOCK_TIME = 15000
// REACT_APP_TRANSACTION_TIME_OUT_BLOCK_NUMBER = 50
// REACT_APP_NAME = 'Keymesh'
// REACT_APP_KVASS_ENDPOINT = 'https://hlskkkzio4.execute-api.ap-northeast-1.amazonaws.com/kvass/'
// REACT_APP_TWITTER_CONSUMER_KEY = '8rBG1xrUBpFgE2T5bDOskGFpv'
// REACT_APP_TWITTER_SECRET_KEY = 'WOL2SCR8RJr38LTBlPEqZz4r6fyU9qqCELBeCE7hmbOcuchnDi'
// REACT_APP_FACEBOOK_APP_ID = '162817767674605'

export default {
  REACT_APP_CONFIRMATION_NUMBER: 1,
  REACT_APP_AVERAGE_BLOCK_TIME: 5000,
  REACT_APP_TRANSACTION_TIME_OUT_BLOCK_NUMBER: 3,
  REACT_APP_NAME: 'Keymesh - dev',
  REACT_APP_KVASS_ENDPOINT: 'https://hlskkkzio4.execute-api.ap-northeast-1.amazonaws.com/kvass/',
  REACT_APP_TWITTER_CONSUMER_KEY: '8rBG1xrUBpFgE2T5bDOskGFpv',
  REACT_APP_TWITTER_SECRET_KEY: 'WOL2SCR8RJr38LTBlPEqZz4r6fyU9qqCELBeCE7hmbOcuchnDi',
  REACT_APP_FACEBOOK_APP_ID: '402106420236062',
}
